### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by GongT** [rschristian/simple-react-lib-in-preact-with-typescript#1]
Greate thanks for your reply！

---

I tried this repo, but I still can not compile it.

I have tried typescript `4.9.5` and `5.1.6`, they give me the same error:

```
src/index.tsx:1:29 - error TS2307: Cannot find module 'react-lib' or its corresponding type declarations.

1 import { FancyButton } from 'react-lib';
                              ~~~~~~~~~~~


Found 1 error in src/index.tsx:1
```

**Comment by rschristian** [comment]
Did you clone & run or did you try to install dependencies yourself? There's a dummy lib placed in `node_modules` that will probably get removed if you actually try to install deps w/ NPM, Yarn, etc.

**Comment by GongT** [comment]
both

![image](https://github.com/rschristian/simple-react-lib-in-preact-with-typescript/assets/2265048/d7aa9233-69e6-4fcf-b1c7-d185edd21902)

**Comment by rschristian** [comment]
Can't reproduce, sorry. It's configured properly so it's something on your end specifically.

**Comment by rschristian** [comment]
You're running `yarn` and creating a `tsconfig.json`. Like I said, don't do that, it'll break the example.

**Comment by GongT** [comment]
Thanks👍. let me check again

**Comment by GongT** [comment]
> You're running `yarn` and creating a `tsconfig.json`. Like I said, don't do that, it'll break the example.

No, I did both.

I got two error if I don't run `yarn`, second one is expected (unknown props foo), but first one is wired.

**Comment by rschristian** [comment]
Sorry, first error is correct (we don't re-export `ReactNode`), second is type checking via path aliases working

Was reading from my phone, missed that in the images

**Comment by rschristian** [comment]
So the "issue" there is that Preact doesn't re-export all of React's types (which we know and try to correct, but it's a moving target as React's types constantly change), not that path aliasing doesn't work, if that makes sense.

**Comment by GongT** [comment]
Ok, clear! I have some ideas now, let me try.

thank you, again! 😆

**Comment by rschristian** [comment]
I'll raise an issue on the repo / implement the alias for `ReactNode`, that's definitely an oversight we'll like to fix, but hopefully this gives you a (rough) idea of how things are meant to be working.

Certainly feel free to create an issue if you run across any further missing types or weird type errors.

**Comment by rschristian** [comment]
https://github.com/preactjs/preact/pull/4077
